#!/bin/bash
# Launches an instance of lemonbar
killall -q lemonbar
killall -q lemonconfig

~/.config/lemonbar/lemonconfig | lemonbar -p -g x24+2 -F "#ffcdd6f4" -B "#ff1e1e2e" -f "HackNerdFont"-12 -f "SourceHanSansJP"-12
