#!/usr/bin/bash
# Outputs a configuration for lemonbar

Workspaces() {
    desktops=$(bspc query -D)
    focused=$(bspc query -D -d focused)

    #desktops=$(echo $desktops | sed "s/$focused/%{F#f38ba8}$focused%{F-}/")

    for desktop in $desktops; do
        desktop=$(echo "$desktop")
        nodes=$(bspc query -N -d $desktop)

        if [[ ! -z "$nodes" ]]
	then
            if [[ "$desktop" = "$focused" ]]
	    then
		desktops=$(echo $desktops | sed "s/$desktop/%{F#f38ba8}%{F-}/")
	    else
		desktops=$(echo $desktops | sed "s/$desktop//")
	    fi
	else 
            if [[ "$desktop" = "$focused" ]]
            then
		desktops=$(echo $desktops | sed "s/$desktop/%{F#f38ba8}%{F-}/")
	    else
		desktops=$(echo $desktops | sed "s/$desktop//")
	    fi
	fi
    done

    echo $desktops
}

Battery() {
	BATTACPI=$(acpi --battery)
	BATPERC=$(echo $BATTACPI | cut -d, -f2 | tr -d '[:space:]')

	if [[ $BATTACPI == *"100%"* ]]
	then
		echo -e -n "\uf00c $BATPERC"
	elif [[ $BATTACPI == *"discharging"* ]]
	then
		BATPERC=${BATPERC::-1}
		if [ $BATPERC -le "10" ]
		then
			echo -e -n "%{F#f38ba8}\uf244"
		elif [ $BATPERC -le "25" ]
		then
			echo -e -n "%{F#f9e2af}\uf243"
		elif [ $BATPERC -le "50" ]
		then
			echo -e -n "\uf242"
		elif [ $BATPERC -le "75" ]
		then
			echo -e -n "\uf241"
		elif [ $BATPERC -le "100" ]
		then
			echo -e -n "\uf240"
		fi
		echo -e " $BATPERC% %{F-}"
	elif [[ $BATTACPI == *"charging"* && $BATTACPI != *"100%"* ]]
	then
		echo -e "\uf0e7 $BATPERC"
	elif [[ $BATTACPI == *"Unknown"* ]]
	then
		echo -e "$BATPERC"
	fi
}


Clock(){
    TIME=$(date "+%H:%M:%S")
    
    echo -e -n " ${TIME}"
}

Sound(){
	NOTMUTED=$( amixer sget Master | grep "\[on\]" )
	if [[ ! -z $NOTMUTED ]] ; then
		VOL=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//g')
		if [[ $VOL -ge 80 ]] ; then
			echo -e "\uf028 ${VOL}%"
		elif [[ $VOL -ge 20 ]] ; then
			echo -e "\uf027 ${VOL}%"
		else
			echo -e "\uf026 ${VOL}%"
		fi
	else
		echo -e "\uf026 M"
	fi
}

Update(){
    echo -e "%{l}%{F-} $(Workspaces)%{c}    %{r}  $(Battery) $(Clock) "
}

while true; do
    Update
    sleep 0.1s
done
