#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

xsetroot -solid "#1e1e2e"
xsetroot -cursor_name Catppuccin-Mocha-Dark
xrandr --output HDMI-0 --auto --left-of eDP-1-1

bspc config pointer_modifier mod1
bspc config pointer_action1 move

bspc config focused_border_color \#45475a
bspc config active_border_color \#313244
bspc config normal_border_color \#313244

xrdb ~/.Xresources
systemctl start NetworkManager.service


~/.config/lemonbar/launchlemon
