#!/bin/bash
# Launches an instance of lemonbar
killall -q lemonbar
killall -q lemonconfig

~/.config/lemonbar/lemonconfig | lemonbar -p -g x16 -F "#FFA9B1D6" -B "#FF1A1B26" -f "HackNerdFontMono"-12 -f "SourceHanSansJP"-12
