#!/usr/bin/bash
# Outputs a configuration for lemonbar

Battery() {
    BATTACPI=$(acpi --battery)
    BATPERC=$(echo $BATTACPI | cut -d, -f2 | tr -d '[:space:]')

    echo -e "$BATPERC"
}


Clock(){
    TIME=$(date "+%I:%M")

    echo -e -n "${TIME}"
}

Update(){
    echo -e "%{l}ひらがな \udb82\udcc7 󰣇 %{r} $(Battery)  $(Clock)"
}

while true; do
    Update
    sleep 0.1s
done
